//! Embedded docs ingest — seeds the Knowledge Base window with the
//! configured documentation corpus on app startup.
//!
//! The docs are baked into the binary at compile time via `build.rs`,
//! which walks the configured root and generates a static array of
//! `(rel_path, title, content)` tuples (`rel_path` = POSIX path
//! relative to the docs root, sans `.md`). On startup this module
//! writes each entry as a `knowledge/article` entity into the system
//! peer's tree at `/{system_pid}/knowledge/articles/{rel_path}` — so
//! the knowledge base mirrors the on-disk directory structure.
//!
//! **Both deployment modes.** Earlier this only ran in Direct mode
//! (it used L0 `ctx.store().put`, which panics on the Worker arm), so
//! the browser/mobile build — which runs Worker mode — showed an empty
//! Knowledge Base while Tauri (Direct) was fine. Now:
//!
//! - **Direct** (Tauri, native tests): synchronous in-process L0 puts
//!   with a cheap per-path skip. Fast, no round trips, immediately
//!   consistent.
//! - **Worker** (browser/mobile): the tree lives in the worker and is
//!   OPFS-persisted, so re-seeding every reload would be pure
//!   round-trip waste. A localStorage fingerprint of the embedded
//!   corpus gates the seed; a docs rebuild changes the fingerprint, so
//!   "get the latest data" still works. Writes go through the
//!   mode-agnostic fire-and-forget `dispatch_write`; the KB window's
//!   subscription surfaces them as they land.

use crate::peers::Peers;

use super::model::{article_path, encode_article};

// Generated by build.rs at compile time. Defines:
//   pub static EMBEDDED_DOCS: &[(&str, &str, &str)] = &[ ... ];
//   tuples are (rel_path, title, content).
include!(concat!(env!("OUT_DIR"), "/embedded_docs.rs"));

/// localStorage key holding the fingerprint of the last successfully
/// seeded corpus (Worker arm only).
#[cfg(target_arch = "wasm32")]
const SEED_FP_KEY: &str = "kb_seed_fingerprint";

/// Cheap fingerprint of the embedded corpus: doc count + total
/// key/content bytes. Changes whenever docs are added/removed or any
/// content's length changes — good enough to detect a rebuild without
/// hashing 50+ MB on every boot. (A content edit that preserves exact
/// byte length wouldn't bump it; acceptable for the POC corpus.)
#[cfg(target_arch = "wasm32")]
fn corpus_fingerprint() -> String {
    let mut bytes = 0usize;
    for &(k, _t, c) in EMBEDDED_DOCS {
        bytes += k.len() + c.len();
    }
    format!("{}:{}", EMBEDDED_DOCS.len(), bytes)
}

#[cfg(target_arch = "wasm32")]
fn local_storage() -> Option<web_sys::Storage> {
    web_sys::window()?.local_storage().ok()?
}

#[cfg(target_arch = "wasm32")]
fn seed_fingerprint_matches(fp: &str) -> bool {
    local_storage()
        .and_then(|s| s.get_item(SEED_FP_KEY).ok().flatten())
        .map(|v| v == fp)
        .unwrap_or(false)
}

#[cfg(target_arch = "wasm32")]
fn store_seed_fingerprint(fp: &str) {
    if let Some(s) = local_storage() {
        let _ = s.set_item(SEED_FP_KEY, fp);
    }
}

/// localStorage key holding the newline-joined list of article keys
/// written by the last successful Worker seed. We track this app-side
/// because the worker's OPFS-persisted tree isn't readable from the
/// app at boot — without it, a corpus change would *union* the new
/// docs on top of stale ones (the "still showing the old docs root"
/// bug) instead of replacing them.
#[cfg(target_arch = "wasm32")]
const SEEDED_KEYS_KEY: &str = "kb_seeded_keys";

#[cfg(target_arch = "wasm32")]
fn load_seeded_keys() -> Vec<String> {
    local_storage()
        .and_then(|s| s.get_item(SEEDED_KEYS_KEY).ok().flatten())
        .map(|v| {
            v.split('\n')
                .filter(|k| !k.is_empty())
                .map(String::from)
                .collect()
        })
        .unwrap_or_default()
}

#[cfg(target_arch = "wasm32")]
fn store_seeded_keys(keys: &[&str]) {
    if let Some(s) = local_storage() {
        let _ = s.set_item(SEEDED_KEYS_KEY, &keys.join("\n"));
    }
}

/// Write all embedded docs into the system peer's knowledge base.
///
/// Called once from `build_wasm_app` after the system peer is set up
/// and before any windows spawn. Mode-aware (see module docs); safe to
/// call on either arm.
pub fn ingest_embedded_docs(peers: &Peers) {
    let pid = peers.primary_peer_id().to_string();

    // Direct arm (in-process tree; also the native unit-test path):
    // synchronous L0 puts, idempotent via a per-path existence check.
    if let Some(pm) = peers.primary_as_direct() {
        // Primary on the Direct arm is proven by the guard above, so the
        // primary's own `PeerContext` is always present — no per-peer
        // arm routing, no default-to-primary footgun (the deleted
        // `peer_context_or_default`).
        let ctx = pm
            .peer_context(&pid)
            .expect("knowledge_base ingest: primary present on Direct arm");
        let mut written = 0usize;
        let mut skipped = 0usize;
        let mut failed = 0usize;
        for &(rel_path, title, content) in EMBEDDED_DOCS {
            let path = article_path(&pid, rel_path);
            if peers.get_entity(&pid, &path).is_some() {
                skipped += 1;
                continue;
            }
            match ctx.store().put(&path, encode_article(title, content)) {
                Ok(_) => written += 1,
                Err(e) => {
                    failed += 1;
                    tracing::warn!(rel_path = %rel_path, error = %e, "knowledge_base ingest: tree_put failed");
                }
            }
        }
        tracing::info!(
            total = EMBEDDED_DOCS.len(),
            written,
            skipped,
            failed,
            "knowledge_base ingest (direct): complete"
        );
    }

    // Worker arm (browser/mobile). fingerprint-gated fire-and-forget.
    // `primary_as_direct().is_none()` ⇒ Worker; native is always
    // Direct so this block is also compile-gated to wasm.
    #[cfg(target_arch = "wasm32")]
    if peers.primary_as_direct().is_none() {
        let fp = corpus_fingerprint();
        if seed_fingerprint_matches(&fp) {
            tracing::info!(
                docs = EMBEDDED_DOCS.len(),
                "knowledge_base ingest (worker): fingerprint match, up to date — skipping"
            );
            return;
        }
        let t0 = js_sys::Date::now();

        // Corpus changed → the seed is authoritative. Remove the
        // previously-seeded articles (tracked in localStorage; the
        // worker's persisted OPFS tree isn't app-readable at boot) so
        // a root/filter change *replaces* rather than unions onto the
        // stale set. NOTE: if a prior seed predates this tracking
        // (empty list), the old set can't be located here — a one-time
        // "Clear site data" is the only way to drop it.
        let prev_keys = load_seeded_keys();
        for old_key in &prev_keys {
            peers.dispatch_remove(&pid, article_path(&pid, old_key));
        }

        let mut keys: Vec<&str> = Vec::with_capacity(EMBEDDED_DOCS.len());
        for &(rel_path, title, content) in EMBEDDED_DOCS {
            let path = article_path(&pid, rel_path);
            peers.dispatch_write(&pid, path, encode_article(title, content));
            keys.push(rel_path);
        }
        let dispatch_ms = js_sys::Date::now() - t0;
        tracing::info!(
            docs = EMBEDDED_DOCS.len(),
            removed_stale = prev_keys.len(),
            dispatch_ms,
            "knowledge_base ingest (worker): re-seeded (authoritative; writes flush async via the proxy)"
        );
        store_seeded_keys(&keys);
        store_seed_fingerprint(&fp);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_docs_default_is_empty_opt_in() {
        // KB_DOCS_ROOT unset (the default for `cargo test` / normal
        // builds) embeds nothing — the KB is an opt-in POC feature.
        // This just asserts the generated symbol exists and links; a
        // populated corpus is exercised by the structural tests below
        // (vacuously true when empty) and the e2e.
        let _ = EMBEDDED_DOCS.len();
    }

    #[test]
    fn embedded_docs_have_unique_keys() {
        let mut keys: Vec<&str> = EMBEDDED_DOCS.iter().map(|(k, _, _)| *k).collect();
        keys.sort();
        for w in keys.windows(2) {
            assert_ne!(w[0], w[1], "duplicate key in embedded docs: {}", w[0]);
        }
    }

    #[test]
    fn embedded_docs_have_titles_and_content() {
        for (key, title, content) in EMBEDDED_DOCS {
            assert!(!key.is_empty(), "embedded doc has empty key");
            assert!(!title.is_empty(), "embedded doc {} has empty title", key);
            assert!(!content.is_empty(), "embedded doc {} has empty content", key);
        }
    }

    #[test]
    fn ingest_writes_articles_to_system_peer() {
        let pm = Peers::new_direct();
        ingest_embedded_docs(&pm);

        let pid = pm.primary_peer_id().to_string();
        let prefix = super::super::model::articles_prefix(&pid);
        let entries = pm.tree_listing(&pid, &prefix);
        assert!(
            entries.len() >= EMBEDDED_DOCS.len(),
            "expected at least {} articles in tree, got {}",
            EMBEDDED_DOCS.len(),
            entries.len()
        );
    }

    #[test]
    fn ingest_is_idempotent() {
        let pm = Peers::new_direct();
        ingest_embedded_docs(&pm);
        let pid = pm.primary_peer_id().to_string();
        let prefix = super::super::model::articles_prefix(&pid);
        let count_after_first = pm.tree_listing(&pid, &prefix).len();

        ingest_embedded_docs(&pm);
        let count_after_second = pm.tree_listing(&pid, &prefix).len();
        assert_eq!(count_after_first, count_after_second);
    }
}
