//! Generic compute-program host — Mount-only (never Author).
//!
//! Runs transferable EXTENSION-COMPUTE programs (Life, Snake, Asteroids —
//! authored once by workbench-go) from their unchanged IR artifacts:
//! read the descriptor at `<root>/interface`, admit by shape capability,
//! seed, clock the tick (`eval(step)` → put `state_path` → refresh
//! `source`-bearing output ports), and let shape drivers render the port
//! entities. The host names no program and decodes no program state —
//! the one rule per port is `if source: put(path, eval(source)); read path`.
//!
//! Contract: `PROPOSAL-APP-CONVENTION-COMPUTE-PROGRAM` + the workbench-go
//! de-facto ABI. Design: `docs/architecture/reviews/
//! DESIGN-COMPUTE-PROGRAM-HOST-POC.md` (F2 answers, arm matrix, tick
//! pipeline). Programs arrive as embedded fixture bundles
//! (`assets/programs/*.json`, regenerated by `make program-fixtures`) and
//! are materialized at their program-relative paths with per-entity hash
//! verification — the F1 "fetch by hash → materialize → eval by path"
//! sequence with "fetch" = embedded fixture until phase 3 swaps in a real
//! peer fetch.

pub mod bundle;
pub mod controls;
pub mod descriptor;
pub mod host;
pub mod input;
pub mod shapes;

#[cfg(test)]
mod oracle_tests;
