// **The cache-immutability rule itself — the shared source of truth (C15).**
//
// Plain `//` comments, not `//!`: this file is `include!`d into the middle of
// `src/cache_policy.rs`, where an inner doc comment is a syntax error. That is
// the price of one source for two crates and it is worth it.
//
// Split out from [`crate::cache_policy`] so that `src-tauri`'s asset server can
// `include!` it **verbatim**. That is the whole point: there is no `[lib]`
// target here to depend on, and a second careful copy of this logic is exactly
// what `REVIEW-2026-08-25` §2.1 found had drifted four ways.
//
// **Nothing in this file may reference paths relative to its own location** —
// no `include_str!`, no `#[path]` module — because it is compiled from two
// different directories. The vector-based tests live in the wrapper module for
// that reason, and the same vectors are re-asserted from `src-tauri`'s side by
// its own test reading the file at its own relative path.
//
// Read the wrapper's module documentation for the rule and why it is shaped
// this way. Do not edit this file without running BOTH `make test` and
// `make test-tauri`.

/// Everything before the first `?` or `#`.
///
/// Load-bearing, and the divergence that made it so: `cors-serve.py` tested the
/// **raw target**, so `/index.html?x=/content/ab/cd/…` classified immutable —
/// in the very file the quickstart tells operators to copy.
fn path_only(target: &str) -> &str {
    let end = target.find(['?', '#']).unwrap_or(target.len());
    &target[..end]
}

fn is_lower_hex(s: &str) -> bool {
    !s.is_empty() && s.bytes().all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
}

/// The content-addressed blob store: `…/content/{aa}/{bb}/{hash}`.
///
/// `aa` and `bb` must be the first four characters of `hash`, which is what
/// makes this a statement about content-addressing rather than about a directory
/// that happens to be called `content`.
fn is_content_addressed_blob(path: &str) -> bool {
    let segs: Vec<&str> = path.split('/').filter(|s| !s.is_empty()).collect();
    let n = segs.len();
    if n < 4 {
        return false;
    }
    let (dir, aa, bb, name) = (segs[n - 4], segs[n - 3], segs[n - 2], segs[n - 1]);
    dir == "content"
        && aa.len() == 2
        && bb.len() == 2
        && is_lower_hex(aa)
        && is_lower_hex(bb)
        && name.len() >= 32
        && is_lower_hex(name)
        && name.as_bytes()[..2] == *aa.as_bytes()
        && name.as_bytes()[2..4] == *bb.as_bytes()
}

/// Trunk's content-hashed output: `entity-browser-<16 hex>.js`,
/// `entity-browser-<16 hex>_bg.wasm`.
///
/// **The `_bg` suffix is load-bearing and one expression of this rule shipped
/// without it** — requiring the hex run to be the last segment classified the
/// real multi-MB wasm, the single biggest thing we serve, as `no-store` and
/// re-downloaded it on every load. The unit test missed it because the fixture
/// filename was *invented* rather than copied from `dist/`; the vector file
/// carries real names for that reason.
///
/// The hex run must reach the extension and there must be something before the
/// dash: `foo-1a2b3c4dxyz.js` is not a build artifact and neither is
/// `-deadbeef12.js`.
fn is_hash_named_bundle(path: &str) -> bool {
    let name = path.rsplit('/').next().unwrap_or(path);
    let Some(stem) = name
        .strip_suffix(".wasm")
        .or_else(|| name.strip_suffix(".js"))
    else {
        return false;
    };
    let stem = stem.strip_suffix("_bg").unwrap_or(stem);
    let Some((head, tail)) = stem.rsplit_once('-') else {
        return false;
    };
    !head.is_empty() && tail.len() >= 8 && is_lower_hex(tail)
}

/// May these bytes be cached hard (`max-age=31536000, immutable`)?
///
/// `false` means `no-store`/revalidate. See the module note: the default is the
/// safe one, and every widening of this predicate is a widening of the set of
/// files a bad deploy can pin for a year.
pub fn is_immutable(target: &str) -> bool {
    let path = path_only(target);
    is_content_addressed_blob(path) || is_hash_named_bundle(path)
}

/// The `Cache-Control` value itself, so a call site cannot get the *mapping*
/// right and the *string* wrong.
pub fn cache_control(target: &str) -> &'static str {
    if is_immutable(target) {
        "public, max-age=31536000, immutable"
    } else {
        "no-store"
    }
}
